#!/usr/bin/env python3
"""figuya theme generator.

Reads palette.toml, derives a WCAG-floored colour set for the light and dark
variants (brand hues fixed, contrast computed not hand-tuned), and writes a
self-contained theme file for each supported app into ./dist.

    python3 generate.py [--preview]

Hue-preserving floor: on a dark background a too-dim colour is lifted toward
white; on a light background it is darkened toward black. Either way the hue is
held and only lightness moves, so every accent clears its WCAG floor against the
background it actually sits on, in both variants.

Nothing here touches your live config — every output lands under ./dist. See the
README for where each port file goes.
"""
import json
import os
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "dist")

# Fixed light/dark poles used to pick a readable foreground on an accent fill.
INK = "2d2220"
PAPER = "fffaf3"


# ---- colour maths -----------------------------------------------------------
def _lin(c):
    c /= 255
    return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4


def _lum(rgb):
    r, g, b = rgb
    return 0.2126 * _lin(r) + 0.7152 * _lin(g) + 0.0722 * _lin(b)


def _hx(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _hs(rgb):
    return "%02x%02x%02x" % rgb


def contrast(fg, bg):
    a, b = sorted((_lum(fg), _lum(bg)), reverse=True)
    return (a + 0.05) / (b + 0.05)


def floor(fg_hex, bg_hex, ratio):
    """Lift (dark bg) or darken (light bg) fg until contrast >= ratio, hue held."""
    fg, bg = _hx(fg_hex), _hx(bg_hex)
    if contrast(fg, bg) >= ratio:
        return _hs(fg)
    toward = (255, 255, 255) if _lum(bg) < 0.5 else (0, 0, 0)
    lo, hi = 0.0, 1.0
    for _ in range(50):
        t = (lo + hi) / 2
        cand = tuple(round(fg[i] + (toward[i] - fg[i]) * t) for i in range(3))
        if contrast(cand, bg) >= ratio:
            hi = t
        else:
            lo = t
    return _hs(tuple(round(fg[i] + (toward[i] - fg[i]) * hi) for i in range(3)))


def mix(h1, h2, t):
    a, b = _hx(h1), _hx(h2)
    return _hs(tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3)))


def on(hexv):
    """Readable foreground (ink or paper) for a fill of colour `hexv`."""
    return INK if contrast(_hx(INK), _hx(hexv)) >= contrast(_hx(PAPER), _hx(hexv)) else PAPER


# ---- palette resolution -----------------------------------------------------
BRAND = ("primary", "secondary", "tertiary", "info", "success", "warning", "error")


def resolve(cfg, variant):
    """Flat dict of hex strings (no '#') for one variant."""
    v = cfg["variant"][variant]
    fl = cfg["floors"]
    bg = v["bg"]
    p = {
        "variant": variant,
        "bg": bg,
        "surface": v["surface"],
        "overlay": v["overlay"],
        "hl_med": v["hl_med"],
        "text": floor(v["text"], bg, fl["text"]),
        "dim": floor(v["dim"], bg, fl["dim"]),
    }
    # Brand accents: floored for legible text (`role`) + raw brand hex for
    # large/non-text UI accents (`role_raw`: cursors, borders, signs).
    for role in BRAND:
        raw = cfg["brand"][role]
        p[role] = floor(raw, bg, fl["accent"])
        p[role + "_raw"] = raw
    # Terminal ANSI hues. Values in [ansi] are either a brand-role name or a hex.
    for slot, ref in cfg["ansi"].items():
        raw = cfg["brand"][ref] if ref in cfg["brand"] else ref
        p["ansi_" + slot] = floor(raw, bg, fl["accent"])
    # ANSI black/white poles, ordered 0 < 8 < 7 < 15 by luminance in both modes.
    if variant == "dark":
        p["c0"], p["c8"] = p["overlay"], p["dim"]
        p["c7"], p["c15"] = mix(p["dim"], p["text"], 0.5), p["text"]
    else:
        p["c0"], p["c8"] = p["text"], p["dim"]
        p["c7"], p["c15"] = mix(p["overlay"], p["surface"], 0.5), p["surface"]
    return p


# ---- io ---------------------------------------------------------------------
_written = []


def write(relpath, body):
    path = os.path.join(OUT, relpath)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(body)
    _written.append(relpath)


def H(p, key):
    return "#" + p[key]


GEN = "figuya — generated by generate.py from palette.toml. Do not hand-edit."


# ── Terminals ────────────────────────────────────────────────────────────────
def _ansi16(p):
    """The 16 ANSI colours (no '#'), in index order."""
    hues = ("ansi_red", "ansi_green", "ansi_yellow",
            "ansi_blue", "ansi_magenta", "ansi_cyan")
    normal = [p["c0"]] + [p[h] for h in hues] + [p["c7"]]
    bright = [p["c8"]] + [p[h] for h in hues] + [p["c15"]]
    return normal + bright


def emit_alacritty(p):
    a = _ansi16(p)
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    body = [f"# {GEN}", "[colors.primary]",
            f'background = "0x{p["bg"]}"', f'foreground = "0x{p["text"]}"', "",
            "[colors.cursor]", f'cursor = "0x{p["primary_raw"]}"',
            f'text = "0x{p["bg"]}"', "",
            "[colors.selection]", f'background = "0x{p["hl_med"]}"',
            f'text = "0x{p["text"]}"', ""]
    for label, off in (("normal", 0), ("bright", 8)):
        body.append(f"[colors.{label}]")
        for i, n in enumerate(names):
            body.append(f'{n} = "0x{a[off + i]}"')
        body.append("")
    write(f"alacritty/figuya-{p['variant']}.toml", "\n".join(body))


def emit_kitty(p):
    a = _ansi16(p)
    lines = [f"# {GEN}",
             f"background  {H(p,'bg')}",
             f"foreground  {H(p,'text')}",
             f"cursor  {H(p,'primary_raw')}",
             f"cursor_text_color  {H(p,'bg')}",
             f"selection_background  {H(p,'hl_med')}",
             f"selection_foreground  {H(p,'text')}",
             f"url_color  {H(p,'info')}", ""]
    for i, c in enumerate(a):
        lines.append(f"color{i}  #{c}")
    write(f"kitty/figuya-{p['variant']}.conf", "\n".join(lines) + "\n")


def emit_wezterm(p):
    a = _ansi16(p)
    ansi = ", ".join(f'"#{c}"' for c in a[:8])
    brights = ", ".join(f'"#{c}"' for c in a[8:])
    body = f"""-- {GEN}
-- WezTerm: copy into ~/.config/wezterm/colors/ or return from your config.
return {{
  foreground = "{H(p,'text')}",
  background = "{H(p,'bg')}",
  cursor_bg = "{H(p,'primary_raw')}",
  cursor_fg = "{H(p,'bg')}",
  cursor_border = "{H(p,'primary_raw')}",
  selection_bg = "{H(p,'hl_med')}",
  selection_fg = "{H(p,'text')}",
  ansi = {{ {ansi} }},
  brights = {{ {brights} }},
}}
"""
    write(f"wezterm/figuya-{p['variant']}.lua", body)


def emit_foot(p):
    a = _ansi16(p)
    lines = [f"# {GEN}", "[colors]",
             f"background={p['bg']}", f"foreground={p['text']}",
             f"selection-background={p['hl_med']}",
             f"selection-foreground={p['text']}",
             f"cursor={p['bg']} {p['primary_raw']}", ""]
    for i in range(8):
        lines.append(f"regular{i}={a[i]}")
    for i in range(8):
        lines.append(f"bright{i}={a[8 + i]}")
    write(f"foot/figuya-{p['variant']}.ini", "\n".join(lines) + "\n")


def emit_ghostty(p):
    a = _ansi16(p)
    lines = [f"# {GEN}",
             f"background = {p['bg']}", f"foreground = {p['text']}",
             f"cursor-color = {p['primary_raw']}",
             f"selection-background = {p['hl_med']}",
             f"selection-foreground = {p['text']}"]
    for i, c in enumerate(a):
        lines.append(f"palette = {i}=#{c}")
    write(f"ghostty/figuya-{p['variant']}", "\n".join(lines) + "\n")


# ── Editors ──────────────────────────────────────────────────────────────────
def _hl_groups(p):
    """(group, fg, bg, opts) highlight rows shared by the nvim colorscheme."""
    fg, bg = p["text"], p["bg"]
    g = [
        # editor UI
        ("Normal", fg, bg, {}),
        ("NormalFloat", fg, p["surface"], {}),
        ("FloatBorder", p["dim"], p["surface"], {}),
        ("ColorColumn", None, p["overlay"], {}),
        ("Cursor", bg, p["primary_raw"], {}),
        ("CursorLine", None, p["hl_med"], {}),
        ("CursorLineNr", p["primary_raw"], None, {"bold": True}),
        ("LineNr", p["dim"], None, {}),
        ("SignColumn", None, bg, {}),
        ("VertSplit", p["overlay"], None, {}),
        ("WinSeparator", p["overlay"], None, {}),
        ("Folded", p["dim"], p["overlay"], {}),
        ("FoldColumn", p["dim"], bg, {}),
        ("Visual", None, p["hl_med"], {}),
        ("Search", bg, p["warning"], {}),
        ("IncSearch", bg, p["primary_raw"], {}),
        ("CurSearch", bg, p["primary_raw"], {}),
        ("MatchParen", p["primary_raw"], p["overlay"], {"bold": True}),
        ("Pmenu", fg, p["surface"], {}),
        ("PmenuSel", bg, p["primary_raw"], {}),
        ("PmenuSbar", None, p["overlay"], {}),
        ("PmenuThumb", None, p["dim"], {}),
        ("StatusLine", fg, p["surface"], {}),
        ("StatusLineNC", p["dim"], p["overlay"], {}),
        ("TabLine", p["dim"], p["overlay"], {}),
        ("TabLineSel", fg, bg, {"bold": True}),
        ("TabLineFill", None, p["overlay"], {}),
        ("WinBar", fg, None, {"bold": True}),
        ("Title", p["primary"], None, {"bold": True}),
        ("Directory", p["info"], None, {}),
        ("NonText", p["dim"], None, {}),
        ("Whitespace", p["overlay"], None, {}),
        ("SpecialKey", p["dim"], None, {}),
        ("EndOfBuffer", p["bg"], None, {}),
        ("ErrorMsg", p["error"], None, {}),
        ("WarningMsg", p["warning"], None, {}),
        ("ModeMsg", p["dim"], None, {}),
        ("MoreMsg", p["info"], None, {}),
        ("Question", p["info"], None, {}),
        ("QuickFixLine", None, p["hl_med"], {}),
        ("WildMenu", bg, p["primary_raw"], {}),
        # syntax (legacy groups)
        ("Comment", p["dim"], None, {"italic": True}),
        ("Constant", p["tertiary"], None, {}),
        ("String", p["success"], None, {}),
        ("Character", p["success"], None, {}),
        ("Number", p["tertiary"], None, {}),
        ("Boolean", p["tertiary"], None, {}),
        ("Float", p["tertiary"], None, {}),
        ("Identifier", fg, None, {}),
        ("Function", p["info"], None, {}),
        ("Statement", p["secondary"], None, {}),
        ("Conditional", p["secondary"], None, {}),
        ("Repeat", p["secondary"], None, {}),
        ("Label", p["secondary"], None, {}),
        ("Operator", p["primary"], None, {}),
        ("Keyword", p["secondary"], None, {}),
        ("Exception", p["error"], None, {}),
        ("PreProc", p["warning"], None, {}),
        ("Include", p["secondary"], None, {}),
        ("Define", p["warning"], None, {}),
        ("Macro", p["warning"], None, {}),
        ("Type", p["warning"], None, {}),
        ("StorageClass", p["warning"], None, {}),
        ("Structure", p["warning"], None, {}),
        ("Typedef", p["warning"], None, {}),
        ("Special", p["primary"], None, {}),
        ("SpecialChar", p["primary"], None, {}),
        ("Tag", p["info"], None, {}),
        ("Delimiter", p["dim"], None, {}),
        ("SpecialComment", p["info"], None, {"italic": True}),
        ("Debug", p["error"], None, {}),
        ("Underlined", p["info"], None, {"underline": True}),
        ("Error", p["error"], None, {}),
        ("Todo", p["primary_raw"], None, {"bold": True}),
        # diagnostics
        ("DiagnosticError", p["error"], None, {}),
        ("DiagnosticWarn", p["warning"], None, {}),
        ("DiagnosticInfo", p["info"], None, {}),
        ("DiagnosticHint", p["secondary"], None, {}),
        ("DiagnosticOk", p["success"], None, {}),
        ("DiagnosticUnderlineError", p["error"], None, {"undercurl": True, "sp": p["error"]}),
        ("DiagnosticUnderlineWarn", p["warning"], None, {"undercurl": True, "sp": p["warning"]}),
        ("DiagnosticUnderlineInfo", p["info"], None, {"undercurl": True, "sp": p["info"]}),
        ("DiagnosticUnderlineHint", p["secondary"], None, {"undercurl": True, "sp": p["secondary"]}),
        # diff / git
        ("DiffAdd", None, mix(p["success"], p["bg"], 0.78), {}),
        ("DiffChange", None, mix(p["info"], p["bg"], 0.82), {}),
        ("DiffDelete", None, mix(p["error"], p["bg"], 0.80), {}),
        ("DiffText", None, mix(p["info"], p["bg"], 0.66), {}),
        ("Added", p["success"], None, {}),
        ("Changed", p["info"], None, {}),
        ("Removed", p["error"], None, {}),
        ("GitSignsAdd", p["success"], None, {}),
        ("GitSignsChange", p["info"], None, {}),
        ("GitSignsDelete", p["error"], None, {}),
        # spell
        ("SpellBad", None, None, {"undercurl": True, "sp": p["error"]}),
        ("SpellCap", None, None, {"undercurl": True, "sp": p["warning"]}),
        ("SpellRare", None, None, {"undercurl": True, "sp": p["secondary"]}),
        ("SpellLocal", None, None, {"undercurl": True, "sp": p["info"]}),
    ]
    # Treesitter captures (link-style, concrete colours so older nvim is fine).
    ts = {
        "@comment": p["dim"], "@punctuation": p["dim"], "@punctuation.bracket": p["dim"],
        "@punctuation.delimiter": p["dim"], "@punctuation.special": p["primary"],
        "@constant": p["tertiary"], "@constant.builtin": p["tertiary"],
        "@constant.macro": p["warning"], "@string": p["success"],
        "@string.escape": p["primary"], "@string.special": p["primary"],
        "@character": p["success"], "@number": p["tertiary"], "@boolean": p["tertiary"],
        "@float": p["tertiary"], "@function": p["info"], "@function.builtin": p["info"],
        "@function.macro": p["warning"], "@function.call": p["info"],
        "@method": p["info"], "@method.call": p["info"], "@constructor": p["warning"],
        "@parameter": fg, "@field": p["tertiary"], "@property": p["tertiary"],
        "@variable": fg, "@variable.builtin": p["primary"], "@variable.member": p["tertiary"],
        "@keyword": p["secondary"], "@keyword.function": p["secondary"],
        "@keyword.operator": p["primary"], "@keyword.return": p["secondary"],
        "@conditional": p["secondary"], "@repeat": p["secondary"], "@label": p["secondary"],
        "@operator": p["primary"], "@exception": p["error"], "@type": p["warning"],
        "@type.builtin": p["warning"], "@type.definition": p["warning"],
        "@namespace": p["warning"], "@module": p["warning"], "@include": p["secondary"],
        "@tag": p["secondary"], "@tag.attribute": p["info"], "@tag.delimiter": p["dim"],
        "@text.title": p["primary"], "@text.uri": p["info"], "@text.literal": p["success"],
        "@markup.heading": p["primary"], "@markup.link": p["info"],
        "@markup.link.url": p["info"], "@markup.raw": p["success"],
        "@markup.list": p["primary"], "@diff.plus": p["success"],
        "@diff.minus": p["error"], "@diff.delta": p["info"],
        # LSP semantic tokens
        "@lsp.type.class": p["warning"], "@lsp.type.enum": p["warning"],
        "@lsp.type.interface": p["warning"], "@lsp.type.struct": p["warning"],
        "@lsp.type.parameter": fg, "@lsp.type.variable": fg,
        "@lsp.type.property": p["tertiary"], "@lsp.type.function": p["info"],
        "@lsp.type.method": p["info"], "@lsp.type.keyword": p["secondary"],
        "@lsp.type.namespace": p["warning"],
    }
    for grp, col in ts.items():
        g.append((grp, col, None, {}))
    return g


def emit_nvim(pd, pl):
    def block(p, indent):
        lines = []
        for grp, fgc, bgc, opts in _hl_groups(p):
            parts = []
            if fgc:
                parts.append(f'fg = "#{fgc}"')
            if bgc:
                parts.append(f'bg = "#{bgc}"')
            if opts.get("sp"):
                parts.append(f'sp = "#{opts["sp"]}"')
            for k in ("bold", "italic", "underline", "undercurl"):
                if opts.get(k):
                    parts.append(f"{k} = true")
            lines.append(f'{indent}set(0, "{grp}", {{ {", ".join(parts)} }})')
        return "\n".join(lines)

    body = f"""-- {GEN}
-- Drop this file in a directory on your 'runtimepath' under colors/ (e.g.
-- ~/.config/nvim/colors/figuya.lua), then `:colorscheme figuya`. The variant
-- follows `:set background=light|dark`.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.g.colors_name = "figuya"

local set = vim.api.nvim_set_hl
if vim.o.background == "light" then
{block(pl, "  ")}
else
{block(pd, "  ")}
end
"""
    write("nvim/colors/figuya.lua", body)


def emit_helix(p):
    # Helix theme: scope = palette-name, with a [palette] table of hexes.
    pal = {
        "bg": p["bg"], "surface": p["surface"], "overlay": p["overlay"],
        "sel": p["hl_med"], "fg": p["text"], "dim": p["dim"],
        "primary": p["primary"], "secondary": p["secondary"], "tertiary": p["tertiary"],
        "info": p["info"], "success": p["success"], "warning": p["warning"],
        "error": p["error"], "accent": p["primary_raw"],
    }
    scopes = [
        ('"ui.background"', '{ bg = "bg" }'),
        ('"ui.text"', '"fg"'),
        ('"ui.window"', '{ fg = "overlay" }'),
        ('"ui.gutter"', '{ bg = "bg" }'),
        ('"ui.linenr"', '{ fg = "dim" }'),
        ('"ui.linenr.selected"', '{ fg = "accent", modifiers = ["bold"] }'),
        ('"ui.cursor"', '{ fg = "bg", bg = "accent" }'),
        ('"ui.cursor.primary"', '{ fg = "bg", bg = "accent" }'),
        ('"ui.cursorline.primary"', '{ bg = "sel" }'),
        ('"ui.selection"', '{ bg = "sel" }'),
        ('"ui.statusline"', '{ fg = "fg", bg = "surface" }'),
        ('"ui.statusline.inactive"', '{ fg = "dim", bg = "overlay" }'),
        ('"ui.popup"', '{ fg = "fg", bg = "surface" }'),
        ('"ui.menu"', '{ fg = "fg", bg = "surface" }'),
        ('"ui.menu.selected"', '{ fg = "bg", bg = "accent" }'),
        ('"ui.help"', '{ fg = "fg", bg = "surface" }'),
        ('"ui.virtual.whitespace"', '{ fg = "overlay" }'),
        ('"ui.virtual.ruler"', '{ bg = "overlay" }'),
        ('"ui.virtual.inlay-hint"', '{ fg = "dim" }'),
        ('"comment"', '{ fg = "dim", modifiers = ["italic"] }'),
        ('"variable"', '"fg"'),
        ('"variable.builtin"', '"primary"'),
        ('"variable.parameter"', '"fg"'),
        ('"variable.other.member"', '"tertiary"'),
        ('"constant"', '"tertiary"'),
        ('"constant.numeric"', '"tertiary"'),
        ('"constant.character.escape"', '"primary"'),
        ('"string"', '"success"'),
        ('"function"', '"info"'),
        ('"function.builtin"', '"info"'),
        ('"function.macro"', '"warning"'),
        ('"keyword"', '"secondary"'),
        ('"keyword.control"', '"secondary"'),
        ('"keyword.operator"', '"primary"'),
        ('"operator"', '"primary"'),
        ('"type"', '"warning"'),
        ('"type.builtin"', '"warning"'),
        ('"constructor"', '"warning"'),
        ('"label"', '"secondary"'),
        ('"namespace"', '"warning"'),
        ('"punctuation"', '"dim"'),
        ('"punctuation.delimiter"', '"dim"'),
        ('"punctuation.bracket"', '"dim"'),
        ('"tag"', '"secondary"'),
        ('"attribute"', '"info"'),
        ('"markup.heading"', '{ fg = "primary", modifiers = ["bold"] }'),
        ('"markup.bold"', '{ modifiers = ["bold"] }'),
        ('"markup.italic"', '{ modifiers = ["italic"] }'),
        ('"markup.link.url"', '{ fg = "info", modifiers = ["underlined"] }'),
        ('"markup.link.text"', '"info"'),
        ('"markup.raw"', '"success"'),
        ('"diff.plus"', '"success"'),
        ('"diff.delta"', '"info"'),
        ('"diff.minus"', '"error"'),
        ('"diagnostic.error"', '{ underline = { color = "error", style = "curl" } }'),
        ('"diagnostic.warning"', '{ underline = { color = "warning", style = "curl" } }'),
        ('"diagnostic.info"', '{ underline = { color = "info", style = "curl" } }'),
        ('"diagnostic.hint"', '{ underline = { color = "secondary", style = "curl" } }'),
        ('"error"', '"error"'),
        ('"warning"', '"warning"'),
        ('"info"', '"info"'),
        ('"hint"', '"secondary"'),
    ]
    lines = [f"# {GEN}", ""]
    for scope, val in scopes:
        lines.append(f"{scope} = {val}")
    lines.append("")
    lines.append("[palette]")
    for k, val in pal.items():
        lines.append(f'{k} = "#{val}"')
    write(f"helix/figuya-{p['variant']}.toml", "\n".join(lines) + "\n")


def emit_vscode_theme(p):
    name = f"figuya-{p['variant']}"
    colors = {
        "editor.background": H(p, "bg"),
        "editor.foreground": H(p, "text"),
        "editorCursor.foreground": H(p, "primary_raw"),
        "editor.lineHighlightBackground": H(p, "hl_med"),
        "editor.selectionBackground": H(p, "hl_med"),
        "editorLineNumber.foreground": H(p, "dim"),
        "editorLineNumber.activeForeground": H(p, "primary_raw"),
        "editorIndentGuide.background1": H(p, "overlay"),
        "editorWhitespace.foreground": H(p, "overlay"),
        "editorWidget.background": H(p, "surface"),
        "editorHoverWidget.background": H(p, "surface"),
        "editorSuggestWidget.background": H(p, "surface"),
        "editorSuggestWidget.selectedBackground": H(p, "hl_med"),
        "editorError.foreground": H(p, "error"),
        "editorWarning.foreground": H(p, "warning"),
        "editorInfo.foreground": H(p, "info"),
        "sideBar.background": H(p, "surface"),
        "sideBar.foreground": H(p, "text"),
        "activityBar.background": H(p, "surface"),
        "activityBar.foreground": H(p, "primary_raw"),
        "statusBar.background": H(p, "overlay"),
        "statusBar.foreground": H(p, "text"),
        "statusBar.noFolderBackground": H(p, "overlay"),
        "statusBar.debuggingBackground": H(p, "primary_raw"),
        "titleBar.activeBackground": H(p, "surface"),
        "titleBar.activeForeground": H(p, "text"),
        "tab.activeBackground": H(p, "bg"),
        "tab.inactiveBackground": H(p, "overlay"),
        "tab.activeForeground": H(p, "text"),
        "tab.inactiveForeground": H(p, "dim"),
        "tab.activeBorderTop": H(p, "primary_raw"),
        "panel.background": H(p, "bg"),
        "terminal.background": H(p, "bg"),
        "terminal.foreground": H(p, "text"),
        "focusBorder": H(p, "primary_raw"),
        "button.background": H(p, "primary_raw"),
        "button.foreground": "#" + on(p["primary_raw"]),
        "list.activeSelectionBackground": H(p, "hl_med"),
        "list.hoverBackground": H(p, "overlay"),
        "badge.background": H(p, "primary_raw"),
        "badge.foreground": "#" + on(p["primary_raw"]),
    }
    a = _ansi16(p)
    tnames = ["Black", "Red", "Green", "Yellow", "Blue", "Magenta", "Cyan", "White"]
    for i, n in enumerate(tnames):
        colors[f"terminal.ansi{n}"] = "#" + a[i]
        colors[f"terminal.ansiBright{n}"] = "#" + a[8 + i]

    def tok(scope, fg, style=None):
        s = {"foreground": "#" + fg}
        if style:
            s["fontStyle"] = style
        return {"scope": scope, "settings": s}

    token_colors = [
        tok("comment", p["dim"], "italic"),
        tok("string", p["success"]),
        tok("constant.numeric", p["tertiary"]),
        tok("constant.language", p["tertiary"]),
        tok("constant.character, constant.other", p["tertiary"]),
        tok("variable", p["text"]),
        tok("variable.language, variable.other.constant", p["primary"]),
        tok("keyword, storage.type, storage.modifier", p["secondary"]),
        tok("keyword.operator", p["primary"]),
        tok("entity.name.function, support.function", p["info"]),
        tok("entity.name.type, support.type, entity.name.class", p["warning"]),
        tok("entity.name.tag", p["secondary"]),
        tok("entity.other.attribute-name", p["info"]),
        tok("variable.parameter", p["text"]),
        tok("punctuation, meta.brace", p["dim"]),
        tok("markup.heading", p["primary"], "bold"),
        tok("markup.bold", p["text"], "bold"),
        tok("markup.italic", p["text"], "italic"),
        tok("markup.inline.raw, markup.fenced_code", p["success"]),
        tok("markup.underline.link", p["info"], "underline"),
        tok("invalid", p["error"]),
    ]
    theme = {
        "name": name,
        "type": p["variant"],
        "colors": colors,
        "tokenColors": token_colors,
    }
    write(f"vscode/themes/{name}-color-theme.json", json.dumps(theme, indent=2) + "\n")


def emit_vscode_package():
    pkg = {
        "name": "figuya",
        "displayName": "Figuya",
        "description": "Warm, high-contrast theme from the Figuya brand palette.",
        "version": "1.0.0",
        "publisher": "tpraetsch",
        "engines": {"vscode": "^1.70.0"},
        "categories": ["Themes"],
        "contributes": {
            "themes": [
                {"label": "Figuya Dark", "uiTheme": "vs-dark",
                 "path": "./themes/figuya-dark-color-theme.json"},
                {"label": "Figuya Light", "uiTheme": "vs",
                 "path": "./themes/figuya-light-color-theme.json"},
            ]
        },
    }
    write("vscode/package.json", json.dumps(pkg, indent=2) + "\n")


# ── CLI tools ─────────────────────────────────────────────────────────────────
def emit_bat(p):
    # Minimal .tmTheme (Sublime plist). Covers the scopes bat highlights most.
    def d(scope, name, fg, style=""):
        extra = f"\n        <key>fontStyle</key>\n        <string>{style}</string>" if style else ""
        return f"""      <dict>
        <key>name</key>
        <string>{name}</string>
        <key>scope</key>
        <string>{scope}</string>
        <key>settings</key>
        <dict>
          <key>foreground</key>
          <string>#{fg}</string>{extra}
        </dict>
      </dict>"""

    items = "\n".join([
        d("comment", "Comment", p["dim"], "italic"),
        d("string", "String", p["success"]),
        d("constant.numeric", "Number", p["tertiary"]),
        d("constant.language", "Built-in constant", p["tertiary"]),
        d("keyword, storage", "Keyword", p["secondary"]),
        d("keyword.operator", "Operator", p["primary"]),
        d("entity.name.function, support.function", "Function", p["info"]),
        d("entity.name.type, support.type, storage.type", "Type", p["warning"]),
        d("entity.name.tag", "Tag", p["secondary"]),
        d("entity.other.attribute-name", "Attribute", p["info"]),
        d("variable", "Variable", p["text"]),
        d("punctuation", "Punctuation", p["dim"]),
        d("markup.heading", "Heading", p["primary"], "bold"),
        d("markup.inserted", "Diff inserted", p["success"]),
        d("markup.deleted", "Diff deleted", p["error"]),
        d("markup.changed", "Diff changed", p["info"]),
    ])
    body = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- {GEN} -->
<plist version="1.0">
<dict>
  <key>name</key>
  <string>figuya-{p['variant']}</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#{p['bg']}</string>
        <key>foreground</key>
        <string>#{p['text']}</string>
        <key>caret</key>
        <string>#{p['primary_raw']}</string>
        <key>lineHighlight</key>
        <string>#{p['hl_med']}</string>
        <key>selection</key>
        <string>#{p['hl_med']}</string>
      </dict>
    </dict>
{items}
  </array>
</dict>
</plist>
"""
    write(f"bat/figuya-{p['variant']}.tmTheme", body)


def emit_delta(pd, pl):
    def section(p):
        v = p["variant"]
        return f"""[delta "figuya-{v}"]
    syntax-theme = figuya-{v}
    minus-style = syntax "#{mix(p['error'], p['bg'], 0.80)}"
    minus-emph-style = syntax "#{mix(p['error'], p['bg'], 0.62)}"
    plus-style = syntax "#{mix(p['success'], p['bg'], 0.80)}"
    plus-emph-style = syntax "#{mix(p['success'], p['bg'], 0.62)}"
    line-numbers-minus-style = "#{p['error']}"
    line-numbers-plus-style = "#{p['success']}"
    line-numbers-zero-style = "#{p['dim']}"
    hunk-header-decoration-style = "#{p['dim']}" box
    file-style = "#{p['primary_raw']}" bold
    file-decoration-style = "#{p['overlay']}" ul
"""
    body = (f"# {GEN}\n"
            "# Activate with:  git config include.path "
            "<path>/figuya.gitconfig  and  delta.features figuya-dark\n\n"
            + section(pd) + "\n" + section(pl))
    write("delta/figuya.gitconfig", body)


def emit_fzf(p):
    c = (f"--color=bg+:#{p['hl_med']},bg:#{p['bg']},spinner:#{p['tertiary']},"
         f"hl:#{p['secondary']} "
         f"--color=fg:#{p['text']},header:#{p['secondary']},info:#{p['info']},"
         f"pointer:#{p['primary_raw']} "
         f"--color=marker:#{p['success']},fg+:#{p['text']},prompt:#{p['primary']},"
         f"hl+:#{p['secondary']} "
         f"--color=border:#{p['overlay']},label:#{p['dim']}")
    body = (f"# {GEN}\n"
            f"# source this file, or append the value to your FZF_DEFAULT_OPTS.\n"
            f'export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS {c}"\n')
    write(f"fzf/figuya-{p['variant']}.sh", body)


def emit_tmux(p):
    body = f"""# {GEN}
# tmux figuya ({p['variant']}) — source from tmux.conf:  source-file <path>
set -g mode-style "fg=#{p['text']},bg=#{p['hl_med']}"
set -g message-style "fg=#{p['text']},bg=#{p['surface']}"
set -g message-command-style "fg=#{p['text']},bg=#{p['surface']}"
set -g pane-border-style "fg=#{p['overlay']}"
set -g pane-active-border-style "fg=#{p['primary_raw']}"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#{p['text']},bg=#{p['surface']}"
set -g status-left "#[fg=#{on(p['primary_raw'])},bg=#{p['primary_raw']},bold] #S #[fg=#{p['primary_raw']},bg=#{p['surface']},nobold]"
set -g status-right "#[fg=#{p['dim']}] %Y-%m-%d #[fg=#{p['info']}]%H:%M "
setw -g window-status-format "#[fg=#{p['dim']},bg=#{p['surface']}] #I #W "
setw -g window-status-current-format "#[fg=#{on(p['primary_raw'])},bg=#{p['primary_raw']},bold] #I #W "
setw -g window-status-separator ""
"""
    write(f"tmux/figuya-{p['variant']}.conf", body)


def emit_zellij(pd, pl):
    def theme(p):
        name = f"figuya-{p['variant']}"
        return f"""    "{name}" {{
        fg "#{p['text']}"
        bg "#{p['bg']}"
        black "#{p['c0']}"
        red "#{p['ansi_red']}"
        green "#{p['ansi_green']}"
        yellow "#{p['ansi_yellow']}"
        blue "#{p['ansi_blue']}"
        magenta "#{p['ansi_magenta']}"
        cyan "#{p['ansi_cyan']}"
        white "#{p['c15']}"
        orange "#{p['primary_raw']}"
    }}"""
    body = (f"// {GEN}\n"
            "// Put under themes/ in your zellij config, then set `theme \"figuya-dark\"`.\n"
            "themes {\n" + theme(pd) + "\n" + theme(pl) + "\n}\n")
    write("zellij/figuya.kdl", body)


# ---- preview ----------------------------------------------------------------
def preview(pd, pl):
    def row(p):
        out = f"\x1b[48;2;{';'.join(map(str, _hx(p['bg'])))}m "
        for role in BRAND + ("text",):
            r, g, b = _hx(p[role])
            out += f"\x1b[38;2;{r};{g};{b}m{role[:4]} "
        return out + "\x1b[0m"
    print("dark : " + row(pd))
    print("light: " + row(pl))


# ---- main -------------------------------------------------------------------
def main():
    with open(os.path.join(HERE, "palette.toml"), "rb") as f:
        cfg = tomllib.load(f)
    pd, pl = resolve(cfg, "dark"), resolve(cfg, "light")

    # editors
    emit_nvim(pd, pl)
    emit_vscode_package()
    # cli (cross-variant)
    emit_delta(pd, pl)
    emit_zellij(pd, pl)
    for p in (pd, pl):
        # terminals
        emit_alacritty(p)
        emit_kitty(p)
        emit_wezterm(p)
        emit_foot(p)
        emit_ghostty(p)
        # editors
        emit_helix(p)
        emit_vscode_theme(p)
        # cli
        emit_bat(p)
        emit_fzf(p)
        emit_tmux(p)

    print(f"figuya: wrote {len(_written)} files to dist/")
    for rel in sorted(_written):
        print("  dist/" + rel)
    if "--preview" in sys.argv:
        print()
        preview(pd, pl)


if __name__ == "__main__":
    main()
